@startuml 退会
autonumber "[000]"
title 退会

actor User
participant Browser
participant WebServer
participant AppServer
participant RDB
participant NoSQL
participant MailServer
participant MailBox
!pragma teoz true

User -> Browser: /habitsリクエスト()
Browser -> WebServer: /habits静的ページ要求()
WebServer --> Browser: 応答()
Browser -> WebServer: startBuzzerSounds.mp3\n音声データ要求()
WebServer --> Browser: 応答()

User -> Browser: ログアウトボタン押下
Browser -> AppServer: DELETE /api/v1.0/logout

AppServer -> NoSQL: リフレッシュトークン削除(メールアドレス)
NoSQL --> AppServer: 応答()
AppServer -> NoSQL: アクセストークン削除(メールアドレス)
NoSQL --> AppServer: 応答()

AppServer --> Browser: 応答(204)
Browser -> Browser: ログアウト完了画面表示
Browser -> Browser: / ホーム画面表示

@enduml