@startuml タスク計画
title タスク計画

actor User
participant Browser
participant WebServer
participant AppServer
participant RDB
participant NoSQL
participant MailServer
participant MailBox
participant Google
!pragma teoz true

autonumber "[000]"
ref over User, Google: ログイン

User -> Browser: /habitsリクエスト()
Browser -> WebServer: /habits静的ページ要求()
WebServer --> Browser: 応答()
Browser -> WebServer: startBuzzerSounds.mp3\n音声データ要求()
WebServer --> Browser: 応答()

' READ ALL
Browser -> AppServer: 計画済みの習慣一覧取得\nGET /api/v1.0/plannedHabits?page=0&size=100
ref over User, Google: 認証・認可
AppServer -> NoSQL: キャッシュ確認\n(PlannedHabit:accountId:page:size)
NoSQL --> AppServer: 応答()
alt キャッシュされている場合
  AppServer -> AppServer: 過去のデータが含まれていないか確認\n(plannedHabitデータ, now)
  alt 過去のデータが含まれていた場合
    AppServer -> RDB: planned_habitテーブル参照\n(accountId, page, size, now)
    note right of AppServer
      過去の習慣データは取得しない
    end note
    RDB --> AppServer: 応答()
    AppServer -> NoSQL: キャッシュ登録\n(PlannedHabit:accountId:page:size, \nplannedHabitデータ)
  end
else キャッシュされていない場合
  AppServer -> RDB: planned_habitテーブル参照\n(accountId, page, size, now)
  note right of AppServer
    過去の習慣データは取得しない
  end note
  RDB --> AppServer: 応答()
  AppServer -> NoSQL: キャッシュ登録\n(PlannedHabit:accountId:page:size, \nplannedHabitデータ)
end

AppServer --> Browser: 応答()
Browser -> Browser: 習慣一覧表示()

' CREATE
User -> Browser: 習慣登録ボタン押下()
Browser -> Browser: /plan/create()遷移
Browser -> AppServer: 習慣登録\nPOST /api/v1.0/plannedHabits\n(title, startTime, endTime, cost)
ref over User, Google: 認証・認可
AppServer -> RDB: 習慣登録\n(accountId, title, startTime, endTime, cost)
RDB --> AppServer: 応答()
AppServer --> Browser: 応答(201)
Browser -> Browser: 習慣登録完了表示()

' DELETE
User -> Browser: 習慣削除ボタン押下()
Browser -> Browser: 確認ダイヤログ表示
User -> Browser: OK押下
Browser -> AppServer: 習慣削除\nDELETE /api/v1.0/plannedHabits/1
ref over User, Google: 認証・認可
AppServer -> RDB: 習慣削除\n(accountId, plannedHabit.id, timestamp + cancelMarginTime)
note right of AppServer
  キャンセルすることが出来る時間は
  起動時にメモリに保持しておく。
end note
RDB --> AppServer: 応答()
alt 更新件数が0件の時
  AppServer --> Browser: 応答(404,エラーメッセージ)
end
AppServer --> Browser: 応答(204)
Browser -> Browser: 習慣削除完了表示()

@enduml
