version: '3.8'

services:
  client:
    image: goodhabits/client:latest
    container_name: client-ctr
    environment:
      - NODE_ENV=development
    ports:
      - '8888:8888'
    volumes:
      - ../../GoodHabitsClient:/root/GoodHabitsClient
    command: sh -c "npm install && npm run dev"
    tty: true
  server:
    image: goodhabits/server:latest
    depends_on:
      - rdb
      - nosql
    container_name: server-ctr
    environment:
      - DD_API_KEY=${DD_API_KEY}
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - '8080:8080'
      - '8000:8000'
    volumes:
      - $HOME/.m2:/root/.m2
      - ../../GoodHabitsServer/target:/app/GoodHabitsServer/target
  rdb:
    image: postgres:13.6
    container_name: rdb-ctr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - DATABASE_HOST=localhost
    ports:
      - "5432:5432"
  nosql:
      image: "redis:latest"
      container_name: nosql-ctr
      ports:
        - "6379:6379"
  dd-agent:
      image: gcr.io/datadoghq/agent:7
      container_name: datadog-ctr
      environment:
        - DD_API_KEY=${DD_API_KEY}
        - DD_SITE=datadoghq.com
        - DD_LOGS_ENABLED=true
        - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
        - DD_AC_EXCLUDE=image:gcr.io/datadoghq/agent
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
        - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
