DROP USER IF EXISTS havetodouser;
DROP DATABASE IF EXISTS havetodo;

CREATE ROLE havetodouser WITH LOGIN SUPERUSER CREATEDB CREATEROLE INHERIT NOREPLICATION CONNECTION
LIMIT
  -1 PASSWORD 'havetodopass';

CREATE DATABASE havetodo OWNER havetodouser;